In [9]:
import pandas as pd
import optuna
import numpy as np

In [ ]:
df_btc = (
    pd.read_csv("BTC_USDT_15m_1769129842087_1771721842087.csv")
    .set_index("datetime")
    .dropna()
)
df_etc = (
    pd.read_csv("ETC_USDT_15m_1769130073376_1771722073376.csv")
    .set_index("datetime")
    .dropna()
)
df_sol = (
    pd.read_csv("SOL_USDT_15m_1769130125699_1771722125699.csv")
    .set_index("datetime")
    .dropna()
)

display(df_btc.head())
display(df_etc.head())
display(df_sol.head())

                         open      high       low     close     volume
datetime
2026-01-23 01:00:00  89518.83  89675.77  89518.83  89596.86  37.345470
2026-01-23 01:15:00  89596.86  89690.60  89593.29  89690.60  28.878564
2026-01-23 01:30:00  89690.60  89860.00  89640.82  89820.00  45.025629
2026-01-23 01:45:00  89820.00  89937.50  89766.00  89932.68  39.038629
2026-01-23 02:00:00  89932.68  89975.90  89793.48  89949.90  56.795418

                      open   high    low  close    volume
datetime
2026-01-23 01:15:00  11.63  11.65  11.63  11.65   19.8245
2026-01-23 01:30:00  11.65  11.69  11.65  11.67  245.9548
2026-01-23 01:45:00  11.67  11.68  11.67  11.68   55.2469
2026-01-23 02:00:00  11.68  11.70  11.68  11.70   19.2683
2026-01-23 02:15:00  11.70  11.70  11.68  11.68    3.9303

                       open    high     low   close     volume
datetime
2026-01-23 01:15:00  128.32  128.57  128.27  128.42  2342.0048
2026-01-23 01:30:00  128.42  128.78  128.33  128.71  3278.7293
2026-01-23 01:45:00  128.71  128.92  128.63  128.90  2657.2998
2026-01-23 02:00:00  128.90  128.96  128.56  128.78  3024.3740
2026-01-23 02:15:00  128.78  128.81  128.40  128.50   484.7823

In [10]:
def backtest(
    df: pd.DataFrame,
    window_rolling_mean: int,
    window_rolling_std: int,
    zscore: float,
    length_rsi: int = 14,
    overbought: float = 70,
    oversold: float = 30,
    adx: float = 20,
    adxlen: int = 14,
) -> dict:
    df_bt = df.copy()
    df_bt.dropna(inplace=True)

    df_bt["mean"] = df_bt["close"].rolling(window=window_rolling_mean).mean()
    df_bt["std"] = df_bt["close"].rolling(window=window_rolling_std).std()
    df_bt["zscore"] = (df_bt["close"] - df_bt["mean"]) / df_bt["std"]

    # --- RSI Calculation ---
    change = df_bt["close"].diff()
    gain = change.clip(lower=0.0)
    loss = -change.clip(upper=0.0)
    avg_gain = gain.ewm(alpha=1 / length_rsi, adjust=False).mean()
    avg_loss = loss.ewm(alpha=1 / length_rsi, adjust=False).mean()
    rs = avg_gain / avg_loss
    df_bt["rsi"] = 100 - (100 / (1 + rs))

    # --- ADX Calculation ---
    tr1 = df_bt["high"] - df_bt["low"]
    tr2 = (df_bt["high"] - df_bt["close"].shift(1)).abs()
    tr3 = (df_bt["low"] - df_bt["close"].shift(1)).abs()
    tr = pd.concat([tr1, tr2, tr3], axis=1).max(axis=1)

    up = df_bt["high"].diff()
    down = -df_bt["low"].diff()

    plusDM = up.where((up > down) & (up > 0), 0.0)
    plusDM.iloc[0] = np.nan
    minusDM = down.where((down > up) & (down > 0), 0.0)
    minusDM.iloc[0] = np.nan

    truerange = tr.ewm(alpha=1 / adxlen, adjust=False).mean()
    plus = (100 * plusDM.ewm(alpha=1 / adxlen, adjust=False).mean() / truerange).ffill()
    minus = (
        100 * minusDM.ewm(alpha=1 / adxlen, adjust=False).mean() / truerange
    ).ffill()

    sum_dm = plus + minus
    sum_dm = sum_dm.replace(0, 1)  # prevent division by zero
    dx = 100 * (plus - minus).abs() / sum_dm
    df_bt["adx"] = dx.ewm(alpha=1 / adxlen, adjust=False).mean()

    # --- Trading Logic ---
    df_bt["signal"] = np.nan

    # Short condition
    short_cond = (
        (df_bt["zscore"] > zscore) & (df_bt["rsi"] > overbought) & (df_bt["adx"] < adx)
    )
    df_bt.loc[short_cond, "signal"] = -1

    # Long condition
    long_cond = (
        (df_bt["zscore"] < -zscore) & (df_bt["rsi"] < oversold) & (df_bt["adx"] < adx)
    )
    df_bt.loc[long_cond, "signal"] = 1

    # Exit condition: zscore crosses 0 (reverts to mean)
    exit_cond = df_bt["zscore"] * df_bt["zscore"].shift(1) < 0
    df_bt.loc[exit_cond, "signal"] = 0

    # Hold position
    df_bt["position"] = df_bt["signal"].ffill().fillna(0)

    # --- Performance Metrics ---
    df_bt["returns"] = df_bt["close"].pct_change()

    # Strategy returns (current position was carried from yesterday)
    df_bt["strategy_ret"] = df_bt["position"].shift(1) * df_bt["returns"]

    total_return = (1 + df_bt["strategy_ret"]).prod() - 1

    # Annualized based on 15-minute timeframe
    periods_per_year = 365 * 24 * 4
    std_dev = df_bt["strategy_ret"].std()
    sharpe_ratio = (
        (df_bt["strategy_ret"].mean() / std_dev * np.sqrt(periods_per_year))
        if std_dev > 0
        else 0
    )

    cum_returns = (1 + df_bt["strategy_ret"]).cumprod()
    running_max = cum_returns.cummax()
    drawdown = (cum_returns - running_max) / running_max
    max_drawdown = drawdown.min()

    winning_trades = len(df_bt[df_bt["strategy_ret"] > 0])
    losing_trades = len(df_bt[df_bt["strategy_ret"] < 0])
    total_trades = winning_trades + losing_trades
    win_rate = (winning_trades / total_trades) if total_trades > 0 else 0

    return {
        "Total Return": total_return,
        "Sharpe Ratio": sharpe_ratio,
        "Max Drawdown": max_drawdown,
        "Win Rate": win_rate,
    }

In [11]:
def run_optimization(df: pd.DataFrame) -> dict:
    def objective(trial: optuna.Trial):
        window_rolling_mean = trial.suggest_int("window_rolling_mean", 5, 100)
        window_rolling_std = trial.suggest_int("window_rolling_std", 5, 100)
        zscore = trial.suggest_float("zscore", 1.0, 3.5)
        length_rsi = trial.suggest_int("length_rsi", 5, 100)
        overbought = trial.suggest_int("overbought", 50, 100)
        oversold = trial.suggest_int("oversold", 0, 50)
        adx = trial.suggest_int("adx", 0, 100)
        adx_len = trial.suggest_int("adx_len", 5, 100)

        try:
            result_bt = backtest(
                df=df,
                window_rolling_mean=window_rolling_mean,
                window_rolling_std=window_rolling_std,
                zscore=zscore,
                length_rsi=length_rsi,
                overbought=overbought,
                oversold=oversold,
                adx=adx,
                adxlen=adx_len,
            )

            sharpe = float(result_bt["Sharpe Ratio"])
            if pd.isna(sharpe) or sharpe == float("inf") or sharpe == float("-inf"):
                return 0.0

            return sharpe

        except Exception as e:
            # Si ocurre algún error inesperado de Pandas, descartamos el trial en lugar de parar toda la optimización
            raise optuna.TrialPruned()

    study = optuna.create_study(direction="maximize")
    study.optimize(objective, n_trials=200)

    print("Best parameters:", study.best_params)
    print("Best Sharpe Ratio:", study.best_value)

    return study.best_params

In [16]:
best_params = run_optimization(df_btc)
result_bt_btc = backtest(
    df=df_btc,
    window_rolling_mean=best_params["window_rolling_mean"],
    window_rolling_std=best_params["window_rolling_std"],
    zscore=best_params["zscore"],
    length_rsi=best_params["length_rsi"],
    overbought=best_params["overbought"],
    oversold=best_params["oversold"],
    adx=best_params["adx"],
    adxlen=best_params["adx_len"],
)
display(result_bt_btc)

[I 2026-02-22 03:05:16,509] A new study created in memory with name: no-name-cc9ad52c-e5f3-4cf4-8c11-16cdf6f6cfee
[I 2026-02-22 03:05:16,519] Trial 0 finished with value: 5.650250502141901 and parameters: {'window_rolling_mean': 46, 'window_rolling_std': 70, 'zscore': 1.4588834736915202, 'length_rsi': 78, 'overbought': 55, 'oversold': 2, 'adx': 87, 'adx_len': 93}. Best is trial 0 with value: 5.650250502141901.
[I 2026-02-22 03:05:16,526] Trial 1 finished with value: 2.3675907979926167 and parameters: {'window_rolling_mean': 41, 'window_rolling_std': 88, 'zscore': 1.7472032274520959, 'length_rsi': 7, 'overbought': 62, 'oversold': 9, 'adx': 37, 'adx_len': 65}. Best is trial 0 with value: 5.650250502141901.
[I 2026-02-22 03:05:16,533] Trial 2 finished with value: -1.6100941715562733 and parameters: {'window_rolling_mean': 61, 'window_rolling_std': 98, 'zscore': 2.8480568389158494, 'length_rsi': 22, 'overbought': 71, 'oversold': 28, 'adx': 91, 'adx_len': 18}. Best is trial 0 with value: 5.650250502141901.
[I 2026-02-22 03:05:16,540] Trial 3 finished with value: 2.9578719507726126 and parameters: {'window_rolling_mean': 80, 'window_rolling_std': 8, 'zscore': 1.131054642413742, 'length_rsi': 50, 'overbought': 67, 'oversold': 5, 'adx': 88, 'adx_len': 66}. Best is trial 0 with value: 5.650250502141901.
[I 2026-02-22 03:05:16,546] Trial 4 finished with value: 6.563192228638709 and parameters: {'window_rolling_mean': 66, 'window_rolling_std': 61, 'zscore': 2.933143512694156, 'length_rsi': 92, 'overbought': 64, 'oversold': 4, 'adx': 66, 'adx_len': 61}. Best is trial 4 with value: 6.563192228638709.
[I 2026-02-22 03:05:16,554] Trial 5 finished with value: 0.0 and parameters: {'window_rolling_mean': 28, 'window_rolling_std': 89, 'zscore': 1.8433607357957327, 'length_rsi': 76, 'overbought': 70, 'oversold': 16, 'adx': 25, 'adx_len': 63}. Best is trial 4 with value: 6.563192228638709.
[I 2026-02-22 03:05:16,561] Trial 6 finished with value: -0.0578820665326663 and parameters: {'window_rolling_mean': 90, 'window_rolling_std': 88, 'zscore': 3.2985633112251245, 'length_rsi': 50, 'overbought': 83, 'oversold': 28, 'adx': 62, 'adx_len': 55}. Best is trial 4 with value: 6.563192228638709.
[I 2026-02-22 03:05:16,568] Trial 7 finished with value: 0.0 and parameters: {'window_rolling_mean': 17, 'window_rolling_std': 34, 'zscore': 2.830483517123814, 'length_rsi': 20, 'overbought': 64, 'oversold': 4, 'adx': 3, 'adx_len': 59}. Best is trial 4 with value: 6.563192228638709.
[I 2026-02-22 03:05:16,575] Trial 8 finished with value: -2.5165527967378605 and parameters: {'window_rolling_mean': 55, 'window_rolling_std': 51, 'zscore': 3.1190748026295596, 'length_rsi': 31, 'overbought': 97, 'oversold': 23, 'adx': 20, 'adx_len': 77}. Best is trial 4 with value: 6.563192228638709.
[I 2026-02-22 03:05:16,581] Trial 9 finished with value: -0.7928971458599756 and parameters: {'window_rolling_mean': 42, 'window_rolling_std': 84, 'zscore': 1.888850164233017, 'length_rsi': 6, 'overbought': 91, 'oversold': 17, 'adx': 84, 'adx_len': 52}. Best is trial 4 with value: 6.563192228638709.
[I 2026-02-22 03:05:16,595] Trial 10 finished with value: -1.6333534832998582 and parameters: {'window_rolling_mean': 77, 'window_rolling_std': 51, 'zscore': 2.518011562626733, 'length_rsi': 96, 'overbought': 80, 'oversold': 44, 'adx': 63, 'adx_len': 31}. Best is trial 4 with value: 6.563192228638709.
[I 2026-02-22 03:05:16,608] Trial 11 finished with value: 3.9353402603621555 and parameters: {'window_rolling_mean': 66, 'window_rolling_std': 69, 'zscore': 1.0445117300557167, 'length_rsi': 87, 'overbought': 53, 'oversold': 3, 'adx': 70, 'adx_len': 97}. Best is trial 4 with value: 6.563192228638709.
[I 2026-02-22 03:05:16,620] Trial 12 finished with value: 4.140254799306787 and parameters: {'window_rolling_mean': 99, 'window_rolling_std': 65, 'zscore': 2.191979084443971, 'length_rsi': 72, 'overbought': 51, 'oversold': 0, 'adx': 99, 'adx_len': 95}. Best is trial 4 with value: 6.563192228638709.
[I 2026-02-22 03:05:16,633] Trial 13 finished with value: 6.096796309184304 and parameters: {'window_rolling_mean': 40, 'window_rolling_std': 34, 'zscore': 1.4846756257655762, 'length_rsi': 67, 'overbought': 58, 'oversold': 13, 'adx': 73, 'adx_len': 82}. Best is trial 4 with value: 6.563192228638709.
[I 2026-02-22 03:05:16,646] Trial 14 finished with value: -2.466930809698632 and parameters: {'window_rolling_mean': 7, 'window_rolling_std': 24, 'zscore': 2.3253949369026126, 'length_rsi': 62, 'overbought': 59, 'oversold': 13, 'adx': 46, 'adx_len': 40}. Best is trial 4 with value: 6.563192228638709.
[I 2026-02-22 03:05:16,659] Trial 15 finished with value: 1.3345222587622927 and parameters: {'window_rolling_mean': 30, 'window_rolling_std': 36, 'zscore': 1.4881717861445853, 'length_rsi': 98, 'overbought': 77, 'oversold': 37, 'adx': 73, 'adx_len': 81}. Best is trial 4 with value: 6.563192228638709.
[I 2026-02-22 03:05:16,672] Trial 16 finished with value: -1.9567178518307187 and parameters: {'window_rolling_mean': 71, 'window_rolling_std': 41, 'zscore': 3.4875976664520563, 'length_rsi': 63, 'overbought': 59, 'oversold': 21, 'adx': 52, 'adx_len': 77}. Best is trial 4 with value: 6.563192228638709.
[I 2026-02-22 03:05:16,685] Trial 17 finished with value: 0.0 and parameters: {'window_rolling_mean': 55, 'window_rolling_std': 16, 'zscore': 2.6319212976400763, 'length_rsi': 88, 'overbought': 73, 'oversold': 12, 'adx': 76, 'adx_len': 44}. Best is trial 4 with value: 6.563192228638709.
[I 2026-02-22 03:05:16,699] Trial 18 finished with value: 1.8831127478742178 and parameters: {'window_rolling_mean': 25, 'window_rolling_std': 59, 'zscore': 2.090754164638797, 'length_rsi': 39, 'overbought': 58, 'oversold': 9, 'adx': 53, 'adx_len': 86}. Best is trial 4 with value: 6.563192228638709.
[I 2026-02-22 03:05:16,713] Trial 19 finished with value: 0.0 and parameters: {'window_rolling_mean': 37, 'window_rolling_std': 27, 'zscore': 1.353415491217429, 'length_rsi': 63, 'overbought': 67, 'oversold': 34, 'adx': 39, 'adx_len': 5}. Best is trial 4 with value: 6.563192228638709.
[I 2026-02-22 03:05:16,728] Trial 20 finished with value: 0.0 and parameters: {'window_rolling_mean': 49, 'window_rolling_std': 42, 'zscore': 3.041473776786869, 'length_rsi': 85, 'overbought': 89, 'oversold': 18, 'adx': 64, 'adx_len': 70}. Best is trial 4 with value: 6.563192228638709.
[I 2026-02-22 03:05:16,743] Trial 21 finished with value: 3.918225375874516 and parameters: {'window_rolling_mean': 49, 'window_rolling_std': 73, 'zscore': 1.4899979697421677, 'length_rsi': 76, 'overbought': 55, 'oversold': 8, 'adx': 80, 'adx_len': 88}. Best is trial 4 with value: 6.563192228638709.
[I 2026-02-22 03:05:16,756] Trial 22 finished with value: 2.6816862698413435 and parameters: {'window_rolling_mean': 64, 'window_rolling_std': 58, 'zscore': 1.6589427662946086, 'length_rsi': 82, 'overbought': 54, 'oversold': 0, 'adx': 100, 'adx_len': 91}. Best is trial 4 with value: 6.563192228638709.
[I 2026-02-22 03:05:16,770] Trial 23 finished with value: 4.300819423491705 and parameters: {'window_rolling_mean': 37, 'window_rolling_std': 80, 'zscore': 1.3255746444650334, 'length_rsi': 70, 'overbought': 50, 'oversold': 6, 'adx': 90, 'adx_len': 100}. Best is trial 4 with value: 6.563192228638709.
[I 2026-02-22 03:05:16,785] Trial 24 finished with value: 0.0 and parameters: {'window_rolling_mean': 48, 'window_rolling_std': 76, 'zscore': 2.0729558352260318, 'length_rsi': 91, 'overbought': 64, 'oversold': 13, 'adx': 68, 'adx_len': 74}. Best is trial 4 with value: 6.563192228638709.
[I 2026-02-22 03:05:16,799] Trial 25 finished with value: -0.5696792250454609 and parameters: {'window_rolling_mean': 19, 'window_rolling_std': 47, 'zscore': 1.2882272417496594, 'length_rsi': 80, 'overbought': 58, 'oversold': 50, 'adx': 80, 'adx_len': 84}. Best is trial 4 with value: 6.563192228638709.
[I 2026-02-22 03:05:16,815] Trial 26 finished with value: 4.301233198653785 and parameters: {'window_rolling_mean': 59, 'window_rolling_std': 62, 'zscore': 2.43183791151244, 'length_rsi': 68, 'overbought': 62, 'oversold': 0, 'adx': 56, 'adx_len': 44}. Best is trial 4 with value: 6.563192228638709.
[I 2026-02-22 03:05:16,828] Trial 27 finished with value: 0.0 and parameters: {'window_rolling_mean': 78, 'window_rolling_std': 55, 'zscore': 1.6149891153614528, 'length_rsi': 56, 'overbought': 68, 'oversold': 13, 'adx': 93, 'adx_len': 70}. Best is trial 4 with value: 6.563192228638709.
[I 2026-02-22 03:05:16,843] Trial 28 finished with value: 3.514662817457438 and parameters: {'window_rolling_mean': 68, 'window_rolling_std': 67, 'zscore': 1.1894770232689738, 'length_rsi': 93, 'overbought': 56, 'oversold': 9, 'adx': 77, 'adx_len': 90}. Best is trial 4 with value: 6.563192228638709.
[I 2026-02-22 03:05:16,858] Trial 29 finished with value: 2.4265879064056057 and parameters: {'window_rolling_mean': 45, 'window_rolling_std': 25, 'zscore': 1.932582616536604, 'length_rsi': 56, 'overbought': 62, 'oversold': 9, 'adx': 60, 'adx_len': 80}. Best is trial 4 with value: 6.563192228638709.
[I 2026-02-22 03:05:16,871] Trial 30 finished with value: 0.0 and parameters: {'window_rolling_mean': 35, 'window_rolling_std': 96, 'zscore': 2.6945034992770047, 'length_rsi': 79, 'overbought': 76, 'oversold': 4, 'adx': 44, 'adx_len': 54}. Best is trial 4 with value: 6.563192228638709.
[I 2026-02-22 03:05:16,886] Trial 31 finished with value: 7.301608047846574 and parameters: {'window_rolling_mean': 57, 'window_rolling_std': 63, 'zscore': 2.446791149503833, 'length_rsi': 69, 'overbought': 61, 'oversold': 0, 'adx': 57, 'adx_len': 40}. Best is trial 31 with value: 7.301608047846574.
[I 2026-02-22 03:05:16,900] Trial 32 finished with value: 1.2662905572912226 and parameters: {'window_rolling_mean': 59, 'window_rolling_std': 69, 'zscore': 2.731814957567355, 'length_rsi': 70, 'overbought': 62, 'oversold': 3, 'adx': 70, 'adx_len': 30}. Best is trial 31 with value: 7.301608047846574.
[I 2026-02-22 03:05:16,914] Trial 33 finished with value: 1.8502681477180325 and parameters: {'window_rolling_mean': 54, 'window_rolling_std': 74, 'zscore': 2.9855706147329473, 'length_rsi': 99, 'overbought': 53, 'oversold': 7, 'adx': 85, 'adx_len': 31}. Best is trial 31 with value: 7.301608047846574.
[I 2026-02-22 03:05:16,929] Trial 34 finished with value: 0.0 and parameters: {'window_rolling_mean': 74, 'window_rolling_std': 62, 'zscore': 2.486270992065691, 'length_rsi': 45, 'overbought': 70, 'oversold': 1, 'adx': 34, 'adx_len': 38}. Best is trial 31 with value: 7.301608047846574.
[I 2026-02-22 03:05:16,943] Trial 35 finished with value: 0.0 and parameters: {'window_rolling_mean': 86, 'window_rolling_std': 47, 'zscore': 3.2211125459372134, 'length_rsi': 73, 'overbought': 66, 'oversold': 11, 'adx': 56, 'adx_len': 21}. Best is trial 31 with value: 7.301608047846574.
[I 2026-02-22 03:05:16,958] Trial 36 finished with value: 2.356084898956001 and parameters: {'window_rolling_mean': 61, 'window_rolling_std': 8, 'zscore': 1.7885345031735662, 'length_rsi': 65, 'overbought': 60, 'oversold': 4, 'adx': 66, 'adx_len': 63}. Best is trial 31 with value: 7.301608047846574.
[I 2026-02-22 03:05:16,973] Trial 37 finished with value: 3.778967447365261 and parameters: {'window_rolling_mean': 84, 'window_rolling_std': 82, 'zscore': 2.8912252433283725, 'length_rsi': 58, 'overbought': 65, 'oversold': 29, 'adx': 93, 'adx_len': 49}. Best is trial 31 with value: 7.301608047846574.
[I 2026-02-22 03:05:16,988] Trial 38 finished with value: 3.066334327863498 and parameters: {'window_rolling_mean': 43, 'window_rolling_std': 32, 'zscore': 2.241571909522437, 'length_rsi': 49, 'overbought': 56, 'oversold': 16, 'adx': 47, 'adx_len': 59}. Best is trial 31 with value: 7.301608047846574.
[I 2026-02-22 03:05:17,001] Trial 39 finished with value: 1.5119592042219798 and parameters: {'window_rolling_mean': 29, 'window_rolling_std': 93, 'zscore': 1.533750075313585, 'length_rsi': 16, 'overbought': 69, 'oversold': 6, 'adx': 84, 'adx_len': 68}. Best is trial 31 with value: 7.301608047846574.
[I 2026-02-22 03:05:17,014] Trial 40 finished with value: 0.0 and parameters: {'window_rolling_mean': 53, 'window_rolling_std': 54, 'zscore': 1.998395852789271, 'length_rsi': 83, 'overbought': 74, 'oversold': 3, 'adx': 10, 'adx_len': 93}. Best is trial 31 with value: 7.301608047846574.
[I 2026-02-22 03:05:17,027] Trial 41 finished with value: 4.312120135765349 and parameters: {'window_rolling_mean': 60, 'window_rolling_std': 63, 'zscore': 2.410075556456838, 'length_rsi': 66, 'overbought': 62, 'oversold': 0, 'adx': 58, 'adx_len': 47}. Best is trial 31 with value: 7.301608047846574.
[I 2026-02-22 03:05:17,040] Trial 42 finished with value: 2.0752811443709906 and parameters: {'window_rolling_mean': 69, 'window_rolling_std': 62, 'zscore': 2.600956714946222, 'length_rsi': 76, 'overbought': 62, 'oversold': 2, 'adx': 61, 'adx_len': 48}. Best is trial 31 with value: 7.301608047846574.
[I 2026-02-22 03:05:17,053] Trial 43 finished with value: 2.876361488861145 and parameters: {'window_rolling_mean': 63, 'window_rolling_std': 78, 'zscore': 2.385798682863731, 'length_rsi': 67, 'overbought': 57, 'oversold': 5, 'adx': 73, 'adx_len': 24}. Best is trial 31 with value: 7.301608047846574.
[I 2026-02-22 03:05:17,067] Trial 44 finished with value: 1.9445123377678304 and parameters: {'window_rolling_mean': 58, 'window_rolling_std': 49, 'zscore': 2.852531014188174, 'length_rsi': 59, 'overbought': 53, 'oversold': 0, 'adx': 58, 'adx_len': 39}. Best is trial 31 with value: 7.301608047846574.
[I 2026-02-22 03:05:17,080] Trial 45 finished with value: 0.0 and parameters: {'window_rolling_mean': 39, 'window_rolling_std': 87, 'zscore': 2.176213324501234, 'length_rsi': 90, 'overbought': 72, 'oversold': 7, 'adx': 66, 'adx_len': 59}. Best is trial 31 with value: 7.301608047846574.
[I 2026-02-22 03:05:17,095] Trial 46 finished with value: 1.8265772166855547 and parameters: {'window_rolling_mean': 46, 'window_rolling_std': 69, 'zscore': 1.7333850618693685, 'length_rsi': 74, 'overbought': 60, 'oversold': 24, 'adx': 30, 'adx_len': 35}. Best is trial 31 with value: 7.301608047846574.
[I 2026-02-22 03:05:17,108] Trial 47 finished with value: 5.501490343207271 and parameters: {'window_rolling_mean': 33, 'window_rolling_std': 42, 'zscore': 3.3798696670065014, 'length_rsi': 52, 'overbought': 52, 'oversold': 20, 'adx': 50, 'adx_len': 44}. Best is trial 31 with value: 7.301608047846574.
[I 2026-02-22 03:05:17,122] Trial 48 finished with value: 5.501490343207271 and parameters: {'window_rolling_mean': 33, 'window_rolling_std': 41, 'zscore': 3.3954774534029055, 'length_rsi': 46, 'overbought': 50, 'oversold': 19, 'adx': 41, 'adx_len': 15}. Best is trial 31 with value: 7.301608047846574.
[I 2026-02-22 03:05:17,136] Trial 49 finished with value: 3.999690528651822 and parameters: {'window_rolling_mean': 24, 'window_rolling_std': 37, 'zscore': 3.1974238462276916, 'length_rsi': 37, 'overbought': 54, 'oversold': 21, 'adx': 53, 'adx_len': 56}. Best is trial 31 with value: 7.301608047846574.
[I 2026-02-22 03:05:17,149] Trial 50 finished with value: 5.615886202118537 and parameters: {'window_rolling_mean': 11, 'window_rolling_std': 28, 'zscore': 3.0557490443298203, 'length_rsi': 52, 'overbought': 51, 'oversold': 27, 'adx': 50, 'adx_len': 64}. Best is trial 31 with value: 7.301608047846574.
[I 2026-02-22 03:05:17,163] Trial 51 finished with value: 4.856296704350336 and parameters: {'window_rolling_mean': 16, 'window_rolling_std': 22, 'zscore': 3.3524240211122254, 'length_rsi': 52, 'overbought': 52, 'oversold': 22, 'adx': 48, 'adx_len': 64}. Best is trial 31 with value: 7.301608047846574.
[I 2026-02-22 03:05:17,177] Trial 52 finished with value: 4.588705075754236 and parameters: {'window_rolling_mean': 8, 'window_rolling_std': 30, 'zscore': 3.0835299936849117, 'length_rsi': 40, 'overbought': 51, 'oversold': 31, 'adx': 51, 'adx_len': 74}. Best is trial 31 with value: 7.301608047846574.
[I 2026-02-22 03:05:17,193] Trial 53 finished with value: -1.476307539617308 and parameters: {'window_rolling_mean': 12, 'window_rolling_std': 21, 'zscore': 3.250635162299352, 'length_rsi': 60, 'overbought': 56, 'oversold': 35, 'adx': 44, 'adx_len': 52}. Best is trial 31 with value: 7.301608047846574.
[I 2026-02-22 03:05:17,208] Trial 54 finished with value: 0.6297199881331665 and parameters: {'window_rolling_mean': 22, 'window_rolling_std': 43, 'zscore': 3.4942463339405316, 'length_rsi': 30, 'overbought': 85, 'oversold': 26, 'adx': 73, 'adx_len': 97}. Best is trial 31 with value: 7.301608047846574.
[I 2026-02-22 03:05:17,222] Trial 55 finished with value: 4.689529180728464 and parameters: {'window_rolling_mean': 51, 'window_rolling_std': 15, 'zscore': 1.0072869544803362, 'length_rsi': 54, 'overbought': 59, 'oversold': 19, 'adx': 63, 'adx_len': 43}. Best is trial 31 with value: 7.301608047846574.
[I 2026-02-22 03:05:17,236] Trial 56 finished with value: 3.1107123158599363 and parameters: {'window_rolling_mean': 42, 'window_rolling_std': 36, 'zscore': 2.953509159850138, 'length_rsi': 48, 'overbought': 55, 'oversold': 26, 'adx': 35, 'adx_len': 84}. Best is trial 31 with value: 7.301608047846574.
[I 2026-02-22 03:05:17,251] Trial 57 finished with value: 1.9027985112463146 and parameters: {'window_rolling_mean': 33, 'window_rolling_std': 28, 'zscore': 3.153119685737141, 'length_rsi': 43, 'overbought': 51, 'oversold': 40, 'adx': 79, 'adx_len': 61}. Best is trial 31 with value: 7.301608047846574.
[I 2026-02-22 03:05:17,265] Trial 58 finished with value: 0.0 and parameters: {'window_rolling_mean': 5, 'window_rolling_std': 56, 'zscore': 2.7783776097850748, 'length_rsi': 79, 'overbought': 97, 'oversold': 15, 'adx': 96, 'adx_len': 76}. Best is trial 31 with value: 7.301608047846574.
[I 2026-02-22 03:05:17,279] Trial 59 finished with value: 2.571294052279603 and parameters: {'window_rolling_mean': 39, 'window_rolling_std': 38, 'zscore': 3.2988744317750998, 'length_rsi': 62, 'overbought': 64, 'oversold': 30, 'adx': 85, 'adx_len': 100}. Best is trial 31 with value: 7.301608047846574.
[I 2026-02-22 03:05:17,293] Trial 60 finished with value: 0.0 and parameters: {'window_rolling_mean': 26, 'window_rolling_std': 51, 'zscore': 1.1705584961122828, 'length_rsi': 87, 'overbought': 79, 'oversold': 11, 'adx': 50, 'adx_len': 80}. Best is trial 31 with value: 7.301608047846574.
[I 2026-02-22 03:05:17,307] Trial 61 finished with value: 5.2020639158441355 and parameters: {'window_rolling_mean': 30, 'window_rolling_std': 43, 'zscore': 3.4194119009934827, 'length_rsi': 95, 'overbought': 51, 'oversold': 21, 'adx': 39, 'adx_len': 8}. Best is trial 31 with value: 7.301608047846574.
[I 2026-02-22 03:05:17,320] Trial 62 finished with value: 5.501490343207271 and parameters: {'window_rolling_mean': 33, 'window_rolling_std': 40, 'zscore': 3.3846569491092398, 'length_rsi': 33, 'overbought': 53, 'oversold': 18, 'adx': 43, 'adx_len': 35}. Best is trial 31 with value: 7.301608047846574.
[I 2026-02-22 03:05:17,335] Trial 63 finished with value: 2.0301018155926642 and parameters: {'window_rolling_mean': 46, 'window_rolling_std': 33, 'zscore': 1.3948279910827839, 'length_rsi': 46, 'overbought': 50, 'oversold': 19, 'adx': 21, 'adx_len': 8}. Best is trial 31 with value: 7.301608047846574.
[I 2026-02-22 03:05:17,351] Trial 64 finished with value: 3.000191755519098 and parameters: {'window_rolling_mean': 51, 'window_rolling_std': 45, 'zscore': 3.0112117776327696, 'length_rsi': 52, 'overbought': 57, 'oversold': 14, 'adx': 39, 'adx_len': 17}. Best is trial 31 with value: 7.301608047846574.
[I 2026-02-22 03:05:17,366] Trial 65 finished with value: 0.9794294670095819 and parameters: {'window_rolling_mean': 20, 'window_rolling_std': 59, 'zscore': 3.115481411088506, 'length_rsi': 55, 'overbought': 54, 'oversold': 26, 'adx': 54, 'adx_len': 28}. Best is trial 31 with value: 7.301608047846574.

Best parameters: {'window_rolling_mean': 42, 'window_rolling_std': 14, 'zscore': 2.4457595889074395, 'length_rsi': 90, 'overbought': 57, 'oversold': 35, 'adx': 75, 'adx_len': 46}
Best Sharpe Ratio: 11.366225415219846

{'Total Return': np.float64(0.1848471298444958),
 'Sharpe Ratio': np.float64(11.366225415219846),
 'Max Drawdown': np.float64(-0.015966794943692263),
 'Win Rate': 0.5888888888888889}

In [17]:
best_params = run_optimization(df_etc)
result_bt_etc = backtest(
    df=df_etc,
    window_rolling_mean=best_params["window_rolling_mean"],
    window_rolling_std=best_params["window_rolling_std"],
    zscore=best_params["zscore"],
    length_rsi=best_params["length_rsi"],
    overbought=best_params["overbought"],
    oversold=best_params["oversold"],
    adx=best_params["adx"],
    adxlen=best_params["adx_len"],
)
display(result_bt_etc)

[I 2026-02-22 03:18:28,496] A new study created in memory with name: no-name-06e4869a-5b8b-4643-9a68-1da7b7a64d03
[I 2026-02-22 03:18:28,505] Trial 0 finished with value: 0.0 and parameters: {'window_rolling_mean': 75, 'window_rolling_std': 86, 'zscore': 2.7857020130495638, 'length_rsi': 97, 'overbought': 71, 'oversold': 25, 'adx': 36, 'adx_len': 57}. Best is trial 0 with value: 0.0.
[I 2026-02-22 03:18:28,512] Trial 1 finished with value: -0.6090813305722289 and parameters: {'window_rolling_mean': 86, 'window_rolling_std': 100, 'zscore': 1.2976495560578005, 'length_rsi': 9, 'overbought': 63, 'oversold': 46, 'adx': 62, 'adx_len': 14}. Best is trial 0 with value: 0.0.
[I 2026-02-22 03:18:28,519] Trial 2 finished with value: 2.9251065825302245 and parameters: {'window_rolling_mean': 17, 'window_rolling_std': 10, 'zscore': 1.3940000153739458, 'length_rsi': 76, 'overbought': 67, 'oversold': 3, 'adx': 87, 'adx_len': 76}. Best is trial 2 with value: 2.9251065825302245.
[I 2026-02-22 03:18:28,526] Trial 3 finished with value: 2.9704363504279 and parameters: {'window_rolling_mean': 50, 'window_rolling_std': 99, 'zscore': 2.549478978757315, 'length_rsi': 80, 'overbought': 61, 'oversold': 37, 'adx': 88, 'adx_len': 27}. Best is trial 3 with value: 2.9704363504279.
[I 2026-02-22 03:18:28,532] Trial 4 finished with value: 1.4655339432235832 and parameters: {'window_rolling_mean': 7, 'window_rolling_std': 87, 'zscore': 2.227360929493992, 'length_rsi': 80, 'overbought': 96, 'oversold': 49, 'adx': 76, 'adx_len': 17}. Best is trial 3 with value: 2.9704363504279.
[I 2026-02-22 03:18:28,538] Trial 5 finished with value: 0.0 and parameters: {'window_rolling_mean': 57, 'window_rolling_std': 61, 'zscore': 1.1689005895412095, 'length_rsi': 70, 'overbought': 93, 'oversold': 13, 'adx': 75, 'adx_len': 51}. Best is trial 3 with value: 2.9704363504279.
[I 2026-02-22 03:18:28,544] Trial 6 finished with value: 0.0 and parameters: {'window_rolling_mean': 46, 'window_rolling_std': 6, 'zscore': 1.399037837692511, 'length_rsi': 31, 'overbought': 84, 'oversold': 14, 'adx': 1, 'adx_len': 44}. Best is trial 3 with value: 2.9704363504279.
[I 2026-02-22 03:18:28,552] Trial 7 finished with value: 4.268643519695113 and parameters: {'window_rolling_mean': 37, 'window_rolling_std': 65, 'zscore': 3.1772535954870227, 'length_rsi': 71, 'overbought': 68, 'oversold': 0, 'adx': 78, 'adx_len': 12}. Best is trial 7 with value: 4.268643519695113.
[I 2026-02-22 03:18:28,557] Trial 8 finished with value: 0.0 and parameters: {'window_rolling_mean': 6, 'window_rolling_std': 11, 'zscore': 3.0042414064659693, 'length_rsi': 22, 'overbought': 86, 'oversold': 38, 'adx': 68, 'adx_len': 46}. Best is trial 7 with value: 4.268643519695113.
[I 2026-02-22 03:18:28,564] Trial 9 finished with value: 0.0 and parameters: {'window_rolling_mean': 57, 'window_rolling_std': 86, 'zscore': 3.0584607809583253, 'length_rsi': 71, 'overbought': 99, 'oversold': 11, 'adx': 95, 'adx_len': 43}. Best is trial 7 with value: 4.268643519695113.
[I 2026-02-22 03:18:28,577] Trial 10 finished with value: -1.818086444044665 and parameters: {'window_rolling_mean': 30, 'window_rolling_std': 43, 'zscore': 3.4059396340378623, 'length_rsi': 46, 'overbought': 52, 'oversold': 0, 'adx': 40, 'adx_len': 84}. Best is trial 7 with value: 4.268643519695113.
[I 2026-02-22 03:18:28,589] Trial 11 finished with value: 0.7201677520914741 and parameters: {'window_rolling_mean': 36, 'window_rolling_std': 51, 'zscore': 2.3233960689795774, 'length_rsi': 100, 'overbought': 57, 'oversold': 32, 'adx': 100, 'adx_len': 6}. Best is trial 7 with value: 4.268643519695113.
[I 2026-02-22 03:18:28,602] Trial 12 finished with value: 0.0 and parameters: {'window_rolling_mean': 70, 'window_rolling_std': 68, 'zscore': 2.4015499696251497, 'length_rsi': 54, 'overbought': 77, 'oversold': 29, 'adx': 47, 'adx_len': 27}. Best is trial 7 with value: 4.268643519695113.
[I 2026-02-22 03:18:28,614] Trial 13 finished with value: -4.520403164806082 and parameters: {'window_rolling_mean': 31, 'window_rolling_std': 33, 'zscore': 1.9107993575778635, 'length_rsi': 56, 'overbought': 60, 'oversold': 20, 'adx': 57, 'adx_len': 25}. Best is trial 7 with value: 4.268643519695113.
[I 2026-02-22 03:18:28,627] Trial 14 finished with value: 0.0 and parameters: {'window_rolling_mean': 45, 'window_rolling_std': 71, 'zscore': 3.359059898359649, 'length_rsi': 79, 'overbought': 76, 'oversold': 37, 'adx': 82, 'adx_len': 28}. Best is trial 7 with value: 4.268643519695113.
[I 2026-02-22 03:18:28,639] Trial 15 finished with value: 0.0 and parameters: {'window_rolling_mean': 72, 'window_rolling_std': 100, 'zscore': 2.7568237977804912, 'length_rsi': 87, 'overbought': 52, 'oversold': 42, 'adx': 24, 'adx_len': 5}. Best is trial 7 with value: 4.268643519695113.
[I 2026-02-22 03:18:28,652] Trial 16 finished with value: 1.9704547246047923 and parameters: {'window_rolling_mean': 20, 'window_rolling_std': 35, 'zscore': 1.8836023526380452, 'length_rsi': 62, 'overbought': 68, 'oversold': 20, 'adx': 89, 'adx_len': 67}. Best is trial 7 with value: 4.268643519695113.
[I 2026-02-22 03:18:28,664] Trial 17 finished with value: -4.9194367622908395 and parameters: {'window_rolling_mean': 99, 'window_rolling_std': 75, 'zscore': 2.628484168514556, 'length_rsi': 38, 'overbought': 58, 'oversold': 7, 'adx': 69, 'adx_len': 37}. Best is trial 7 with value: 4.268643519695113.
[I 2026-02-22 03:18:28,677] Trial 18 finished with value: 0.0 and parameters: {'window_rolling_mean': 46, 'window_rolling_std': 25, 'zscore': 3.1140258554866653, 'length_rsi': 89, 'overbought': 80, 'oversold': 34, 'adx': 56, 'adx_len': 33}. Best is trial 7 with value: 4.268643519695113.
[I 2026-02-22 03:18:28,689] Trial 19 finished with value: 5.170467166774155 and parameters: {'window_rolling_mean': 65, 'window_rolling_std': 55, 'zscore': 3.4983628839538436, 'length_rsi': 62, 'overbought': 65, 'oversold': 26, 'adx': 81, 'adx_len': 96}. Best is trial 19 with value: 5.170467166774155.
[I 2026-02-22 03:18:28,702] Trial 20 finished with value: 5.170467166774155 and parameters: {'window_rolling_mean': 60, 'window_rolling_std': 55, 'zscore': 3.4312787968344027, 'length_rsi': 62, 'overbought': 71, 'oversold': 19, 'adx': 26, 'adx_len': 97}. Best is trial 19 with value: 5.170467166774155.
[I 2026-02-22 03:18:28,715] Trial 21 finished with value: 5.170467166774155 and parameters: {'window_rolling_mean': 60, 'window_rolling_std': 51, 'zscore': 3.4321397560401663, 'length_rsi': 63, 'overbought': 70, 'oversold': 20, 'adx': 18, 'adx_len': 99}. Best is trial 19 with value: 5.170467166774155.
[I 2026-02-22 03:18:28,728] Trial 22 finished with value: 0.0 and parameters: {'window_rolling_mean': 64, 'window_rolling_std': 56, 'zscore': 3.456709070758464, 'length_rsi': 62, 'overbought': 73, 'oversold': 20, 'adx': 16, 'adx_len': 100}. Best is trial 19 with value: 5.170467166774155.
[I 2026-02-22 03:18:28,741] Trial 23 finished with value: -2.082374727882266 and parameters: {'window_rolling_mean': 81, 'window_rolling_std': 48, 'zscore': 3.4855784375992966, 'length_rsi': 42, 'overbought': 65, 'oversold': 25, 'adx': 21, 'adx_len': 97}. Best is trial 19 with value: 5.170467166774155.
[I 2026-02-22 03:18:28,755] Trial 24 finished with value: 0.0 and parameters: {'window_rolling_mean': 90, 'window_rolling_std': 43, 'zscore': 3.2697435936142067, 'length_rsi': 62, 'overbought': 80, 'oversold': 25, 'adx': 7, 'adx_len': 90}. Best is trial 19 with value: 5.170467166774155.
[I 2026-02-22 03:18:28,769] Trial 25 finished with value: 5.170467166774155 and parameters: {'window_rolling_mean': 63, 'window_rolling_std': 57, 'zscore': 2.965310767432199, 'length_rsi': 49, 'overbought': 71, 'oversold': 18, 'adx': 31, 'adx_len': 83}. Best is trial 19 with value: 5.170467166774155.
[I 2026-02-22 03:18:28,783] Trial 26 finished with value: 0.0 and parameters: {'window_rolling_mean': 63, 'window_rolling_std': 33, 'zscore': 2.882470074632413, 'length_rsi': 55, 'overbought': 87, 'oversold': 28, 'adx': 9, 'adx_len': 92}. Best is trial 19 with value: 5.170467166774155.
[I 2026-02-22 03:18:28,796] Trial 27 finished with value: 0.0 and parameters: {'window_rolling_mean': 55, 'window_rolling_std': 78, 'zscore': 3.2409855343045066, 'length_rsi': 65, 'overbought': 72, 'oversold': 16, 'adx': 46, 'adx_len': 69}. Best is trial 19 with value: 5.170467166774155.
[I 2026-02-22 03:18:28,810] Trial 28 finished with value: -4.209690373499084 and parameters: {'window_rolling_mean': 79, 'window_rolling_std': 44, 'zscore': 3.487204325726508, 'length_rsi': 38, 'overbought': 56, 'oversold': 8, 'adx': 25, 'adx_len': 85}. Best is trial 19 with value: 5.170467166774155.
[I 2026-02-22 03:18:28,824] Trial 29 finished with value: -4.840961649924585 and parameters: {'window_rolling_mean': 68, 'window_rolling_std': 59, 'zscore': 2.842536049755374, 'length_rsi': 26, 'overbought': 65, 'oversold': 24, 'adx': 36, 'adx_len': 62}. Best is trial 19 with value: 5.170467166774155.
[I 2026-02-22 03:18:28,837] Trial 30 finished with value: 0.0 and parameters: {'window_rolling_mean': 76, 'window_rolling_std': 50, 'zscore': 3.26153348461456, 'length_rsi': 91, 'overbought': 79, 'oversold': 22, 'adx': 15, 'adx_len': 75}. Best is trial 19 with value: 5.170467166774155.
[I 2026-02-22 03:18:28,852] Trial 31 finished with value: 5.170467166774155 and parameters: {'window_rolling_mean': 61, 'window_rolling_std': 55, 'zscore': 2.960715016703305, 'length_rsi': 48, 'overbought': 71, 'oversold': 17, 'adx': 30, 'adx_len': 91}. Best is trial 19 with value: 5.170467166774155.
[I 2026-02-22 03:18:28,865] Trial 32 finished with value: 2.710490783488185 and parameters: {'window_rolling_mean': 66, 'window_rolling_std': 63, 'zscore': 3.138338675255361, 'length_rsi': 49, 'overbought': 74, 'oversold': 28, 'adx': 35, 'adx_len': 82}. Best is trial 19 with value: 5.170467166774155.
[I 2026-02-22 03:18:28,879] Trial 33 finished with value: 5.4881427251710075 and parameters: {'window_rolling_mean': 88, 'window_rolling_std': 39, 'zscore': 3.3008651793130177, 'length_rsi': 59, 'overbought': 70, 'oversold': 18, 'adx': 42, 'adx_len': 96}. Best is trial 33 with value: 5.4881427251710075.
[I 2026-02-22 03:18:28,893] Trial 34 finished with value: -1.6575181544932007 and parameters: {'window_rolling_mean': 94, 'window_rolling_std': 23, 'zscore': 3.3033420631996715, 'length_rsi': 58, 'overbought': 63, 'oversold': 10, 'adx': 42, 'adx_len': 95}. Best is trial 33 with value: 5.4881427251710075.
[I 2026-02-22 03:18:28,908] Trial 35 finished with value: 5.4881427251710075 and parameters: {'window_rolling_mean': 85, 'window_rolling_std': 36, 'zscore': 2.7386923884937078, 'length_rsi': 68, 'overbought': 69, 'oversold': 31, 'adx': 54, 'adx_len': 100}. Best is trial 33 with value: 5.4881427251710075.
[I 2026-02-22 03:18:28,921] Trial 36 finished with value: 1.1014726983703647 and parameters: {'window_rolling_mean': 81, 'window_rolling_std': 38, 'zscore': 2.69283285772174, 'length_rsi': 69, 'overbought': 65, 'oversold': 32, 'adx': 53, 'adx_len': 76}. Best is trial 33 with value: 5.4881427251710075.
[I 2026-02-22 03:18:28,935] Trial 37 finished with value: -1.3597110980212916 and parameters: {'window_rolling_mean': 89, 'window_rolling_std': 29, 'zscore': 2.0461956641870795, 'length_rsi': 75, 'overbought': 62, 'oversold': 30, 'adx': 62, 'adx_len': 87}. Best is trial 33 with value: 5.4881427251710075.
[I 2026-02-22 03:18:28,949] Trial 38 finished with value: -0.4603988320069391 and parameters: {'window_rolling_mean': 86, 'window_rolling_std': 18, 'zscore': 1.6313933234201685, 'length_rsi': 11, 'overbought': 68, 'oversold': 23, 'adx': 64, 'adx_len': 79}. Best is trial 33 with value: 5.4881427251710075.
[I 2026-02-22 03:18:28,962] Trial 39 finished with value: 5.942719091934243 and parameters: {'window_rolling_mean': 99, 'window_rolling_std': 43, 'zscore': 2.511937579194517, 'length_rsi': 76, 'overbought': 67, 'oversold': 14, 'adx': 49, 'adx_len': 94}. Best is trial 39 with value: 5.942719091934243.
[I 2026-02-22 03:18:28,977] Trial 40 finished with value: -1.5990604871317415 and parameters: {'window_rolling_mean': 97, 'window_rolling_std': 17, 'zscore': 2.1498115015513317, 'length_rsi': 84, 'overbought': 60, 'oversold': 14, 'adx': 49, 'adx_len': 93}. Best is trial 39 with value: 5.942719091934243.
[I 2026-02-22 03:18:28,990] Trial 41 finished with value: 5.827465843020787 and parameters: {'window_rolling_mean': 95, 'window_rolling_std': 39, 'zscore': 2.490158967364929, 'length_rsi': 67, 'overbought': 67, 'oversold': 15, 'adx': 43, 'adx_len': 100}. Best is trial 39 with value: 5.942719091934243.
[I 2026-02-22 03:18:29,004] Trial 42 finished with value: 1.2593323379306445 and parameters: {'window_rolling_mean': 93, 'window_rolling_std': 41, 'zscore': 2.44211073254038, 'length_rsi': 75, 'overbought': 65, 'oversold': 4, 'adx': 39, 'adx_len': 100}. Best is trial 39 with value: 5.942719091934243.
[I 2026-02-22 03:18:29,018] Trial 43 finished with value: 5.4881427251710075 and parameters: {'window_rolling_mean': 85, 'window_rolling_std': 46, 'zscore': 2.5305019451435062, 'length_rsi': 71, 'overbought': 68, 'oversold': 12, 'adx': 53, 'adx_len': 88}. Best is trial 39 with value: 5.942719091934243.
[I 2026-02-22 03:18:29,031] Trial 44 finished with value: 5.4881427251710075 and parameters: {'window_rolling_mean': 85, 'window_rolling_std': 38, 'zscore': 2.520990352186211, 'length_rsi': 83, 'overbought': 68, 'oversold': 12, 'adx': 44, 'adx_len': 89}. Best is trial 39 with value: 5.942719091934243.
[I 2026-02-22 03:18:29,046] Trial 45 finished with value: 0.0 and parameters: {'window_rolling_mean': 100, 'window_rolling_std': 29, 'zscore': 2.5695173561292566, 'length_rsi': 70, 'overbought': 75, 'oversold': 15, 'adx': 53, 'adx_len': 89}. Best is trial 39 with value: 5.942719091934243.
[I 2026-02-22 03:18:29,060] Trial 46 finished with value: 5.827465843020787 and parameters: {'window_rolling_mean': 95, 'window_rolling_std': 46, 'zscore': 2.32826031973432, 'length_rsi': 68, 'overbought': 69, 'oversold': 8, 'adx': 71, 'adx_len': 56}. Best is trial 39 with value: 5.942719091934243.
[I 2026-02-22 03:18:29,074] Trial 47 finished with value: 0.0 and parameters: {'window_rolling_mean': 94, 'window_rolling_std': 39, 'zscore': 2.267189025103159, 'length_rsi': 77, 'overbought': 77, 'oversold': 4, 'adx': 71, 'adx_len': 54}. Best is trial 39 with value: 5.942719091934243.
[I 2026-02-22 03:18:29,088] Trial 48 finished with value: -4.686685462176623 and parameters: {'window_rolling_mean': 89, 'window_rolling_std': 28, 'zscore': 2.355664082784156, 'length_rsi': 93, 'overbought': 55, 'oversold': 8, 'adx': 62, 'adx_len': 50}. Best is trial 39 with value: 5.942719091934243.
[I 2026-02-22 03:18:29,102] Trial 49 finished with value: 0.0 and parameters: {'window_rolling_mean': 96, 'window_rolling_std': 33, 'zscore': 2.1421918346572153, 'length_rsi': 67, 'overbought': 83, 'oversold': 2, 'adx': 49, 'adx_len': 69}. Best is trial 39 with value: 5.942719091934243.
[I 2026-02-22 03:18:29,116] Trial 50 finished with value: -2.082374727882266 and parameters: {'window_rolling_mean': 75, 'window_rolling_std': 47, 'zscore': 2.781582231026221, 'length_rsi': 82, 'overbought': 60, 'oversold': 10, 'adx': 58, 'adx_len': 79}. Best is trial 39 with value: 5.942719091934243.
[I 2026-02-22 03:18:29,130] Trial 51 finished with value: 5.4881427251710075 and parameters: {'window_rolling_mean': 85, 'window_rolling_std': 46, 'zscore': 2.4947781901231396, 'length_rsi': 73, 'overbought': 67, 'oversold': 6, 'adx': 52, 'adx_len': 94}. Best is trial 39 with value: 5.942719091934243.
[I 2026-02-22 03:18:29,144] Trial 52 finished with value: 5.942719091934243 and parameters: {'window_rolling_mean': 100, 'window_rolling_std': 35, 'zscore': 2.6153245797073805, 'length_rsi': 57, 'overbought': 69, 'oversold': 13, 'adx': 73, 'adx_len': 86}. Best is trial 39 with value: 5.942719091934243.
[I 2026-02-22 03:18:29,158] Trial 53 finished with value: 5.712210879153212 and parameters: {'window_rolling_mean': 91, 'window_rolling_std': 36, 'zscore': 2.6923843587220557, 'length_rsi': 58, 'overbought': 70, 'oversold': 14, 'adx': 73, 'adx_len': 60}. Best is trial 39 with value: 5.942719091934243.
[I 2026-02-22 03:18:29,174] Trial 54 finished with value: 0.0 and parameters: {'window_rolling_mean': 90, 'window_rolling_std': 41, 'zscore': 1.9210860322150134, 'length_rsi': 57, 'overbought': 73, 'oversold': 14, 'adx': 74, 'adx_len': 62}. Best is trial 39 with value: 5.942719091934243.
[I 2026-02-22 03:18:29,189] Trial 55 finished with value: 1.5289346877932606 and parameters: {'window_rolling_mean': 100, 'window_rolling_std': 22, 'zscore': 2.6108796460552455, 'length_rsi': 53, 'overbought': 66, 'oversold': 10, 'adx': 85, 'adx_len': 60}. Best is trial 39 with value: 5.942719091934243.
[I 2026-02-22 03:18:29,203] Trial 56 finished with value: 5.827465843020787 and parameters: {'window_rolling_mean': 96, 'window_rolling_std': 32, 'zscore': 1.0410199663533426, 'length_rsi': 58, 'overbought': 70, 'oversold': 16, 'adx': 66, 'adx_len': 41}. Best is trial 39 with value: 5.942719091934243.
[I 2026-02-22 03:18:29,218] Trial 57 finished with value: -4.719786358659397 and parameters: {'window_rolling_mean': 93, 'window_rolling_std': 26, 'zscore': 1.0797513539431782, 'length_rsi': 44, 'overbought': 62, 'oversold': 13, 'adx': 66, 'adx_len': 39}. Best is trial 39 with value: 5.942719091934243.
[I 2026-02-22 03:18:29,232] Trial 58 finished with value: 0.0 and parameters: {'window_rolling_mean': 96, 'window_rolling_std': 34, 'zscore': 1.3296170662965385, 'length_rsi': 52, 'overbought': 75, 'oversold': 16, 'adx': 77, 'adx_len': 50}. Best is trial 39 with value: 5.942719091934243.
[I 2026-02-22 03:18:29,246] Trial 59 finished with value: -1.3609895714863232 and parameters: {'window_rolling_mean': 100, 'window_rolling_std': 31, 'zscore': 2.664065351463752, 'length_rsi': 59, 'overbought': 63, 'oversold': 9, 'adx': 93, 'adx_len': 45}. Best is trial 39 with value: 5.942719091934243.
[I 2026-02-22 03:18:29,261] Trial 60 finished with value: 0.0 and parameters: {'window_rolling_mean': 92, 'window_rolling_std': 20, 'zscore': 1.5772829754443702, 'length_rsi': 66, 'overbought': 73, 'oversold': 5, 'adx': 72, 'adx_len': 41}. Best is trial 39 with value: 5.942719091934243.
[I 2026-02-22 03:18:29,275] Trial 61 finished with value: 5.692079605232035 and parameters: {'window_rolling_mean': 98, 'window_rolling_std': 41, 'zscore': 2.250982812680271, 'length_rsi': 59, 'overbought': 70, 'oversold': 16, 'adx': 80, 'adx_len': 22}. Best is trial 39 with value: 5.942719091934243.
[I 2026-02-22 03:18:29,290] Trial 62 finished with value: 5.827465843020787 and parameters: {'window_rolling_mean': 97, 'window_rolling_std': 36, 'zscore': 2.2966828361005174, 'length_rsi': 52, 'overbought': 70, 'oversold': 12, 'adx': 80, 'adx_len': 10}. Best is trial 39 with value: 5.942719091934243.
[I 2026-02-22 03:18:29,305] Trial 63 finished with value: 1.3386606102167316 and parameters: {'window_rolling_mean': 95, 'window_rolling_std': 36, 'zscore': 2.4253787494759136, 'length_rsi': 52, 'overbought': 67, 'oversold': 12, 'adx': 69, 'adx_len': 13}. Best is trial 39 with value: 5.942719091934243.
[I 2026-02-22 03:18:29,319] Trial 64 finished with value: -0.03753832470194093 and parameters: {'window_rolling_mean': 12, 'window_rolling_std': 51, 'zscore': 2.3159368194988117, 'length_rsi': 40, 'overbought': 72, 'oversold': 14, 'adx': 85, 'adx_len': 9}. Best is trial 39 with value: 5.942719091934243.
[I 2026-02-22 03:18:29,333] Trial 65 finished with value: 0.0 and parameters: {'window_rolling_mean': 91, 'window_rolling_std': 31, 'zscore': 2.1795087513784157, 'length_rsi': 63, 'overbought': 78, 'oversold': 7, 'adx': 58, 'adx_len': 18}. Best is trial 39 with value: 5.942719091934243.

Best parameters: {'window_rolling_mean': 97, 'window_rolling_std': 16, 'zscore': 2.5446187017058297, 'length_rsi': 57, 'overbought': 72, 'oversold': 34, 'adx': 66, 'adx_len': 81}
Best Sharpe Ratio: 7.008143008367439

{'Total Return': np.float64(0.2339213159376068),
 'Sharpe Ratio': np.float64(7.008143008367439),
 'Max Drawdown': np.float64(-0.059760956175298384),
 'Win Rate': 0.5736434108527132}

In [18]:
best_params = run_optimization(df_sol)
result_bt_sol = backtest(
    df=df_sol,
    window_rolling_mean=best_params["window_rolling_mean"],
    window_rolling_std=best_params["window_rolling_std"],
    zscore=best_params["zscore"],
    length_rsi=best_params["length_rsi"],
    overbought=best_params["overbought"],
    oversold=best_params["oversold"],
    adx=best_params["adx"],
    adxlen=best_params["adx_len"],
)
display(result_bt_sol)

[I 2026-02-22 03:23:35,138] A new study created in memory with name: no-name-f1ab4dda-8e39-4e8f-bad4-ebda9a5d945a
[I 2026-02-22 03:23:35,144] Trial 0 finished with value: -0.98064842727977 and parameters: {'window_rolling_mean': 47, 'window_rolling_std': 42, 'zscore': 1.9547019775145738, 'length_rsi': 86, 'overbought': 84, 'oversold': 39, 'adx': 44, 'adx_len': 85}. Best is trial 0 with value: -0.98064842727977.
[I 2026-02-22 03:23:35,154] Trial 1 finished with value: -0.8926534658062485 and parameters: {'window_rolling_mean': 57, 'window_rolling_std': 72, 'zscore': 1.0717599831081737, 'length_rsi': 29, 'overbought': 96, 'oversold': 26, 'adx': 16, 'adx_len': 74}. Best is trial 1 with value: -0.8926534658062485.
[I 2026-02-22 03:23:35,162] Trial 2 finished with value: -3.380180003397883 and parameters: {'window_rolling_mean': 97, 'window_rolling_std': 15, 'zscore': 1.2547278777643025, 'length_rsi': 36, 'overbought': 61, 'oversold': 41, 'adx': 87, 'adx_len': 33}. Best is trial 1 with value: -0.8926534658062485.
[I 2026-02-22 03:23:35,169] Trial 3 finished with value: 0.0 and parameters: {'window_rolling_mean': 98, 'window_rolling_std': 49, 'zscore': 2.6960992835733717, 'length_rsi': 52, 'overbought': 88, 'oversold': 16, 'adx': 48, 'adx_len': 31}. Best is trial 3 with value: 0.0.
[I 2026-02-22 03:23:35,176] Trial 4 finished with value: 0.0 and parameters: {'window_rolling_mean': 74, 'window_rolling_std': 92, 'zscore': 1.866369972130712, 'length_rsi': 7, 'overbought': 51, 'oversold': 25, 'adx': 4, 'adx_len': 18}. Best is trial 3 with value: 0.0.
[I 2026-02-22 03:23:35,182] Trial 5 finished with value: 1.353270113741884 and parameters: {'window_rolling_mean': 27, 'window_rolling_std': 98, 'zscore': 1.0292998402731541, 'length_rsi': 38, 'overbought': 99, 'oversold': 33, 'adx': 86, 'adx_len': 17}. Best is trial 5 with value: 1.353270113741884.
[I 2026-02-22 03:23:35,189] Trial 6 finished with value: 0.8747737396269916 and parameters: {'window_rolling_mean': 32, 'window_rolling_std': 85, 'zscore': 2.5213452193060224, 'length_rsi': 42, 'overbought': 52, 'oversold': 13, 'adx': 15, 'adx_len': 92}. Best is trial 5 with value: 1.353270113741884.
[I 2026-02-22 03:23:35,195] Trial 7 finished with value: 1.1583330490458523 and parameters: {'window_rolling_mean': 26, 'window_rolling_std': 59, 'zscore': 1.160215648418651, 'length_rsi': 51, 'overbought': 57, 'oversold': 20, 'adx': 53, 'adx_len': 23}. Best is trial 5 with value: 1.353270113741884.
[I 2026-02-22 03:23:35,202] Trial 8 finished with value: 0.0 and parameters: {'window_rolling_mean': 58, 'window_rolling_std': 21, 'zscore': 1.3970208750429736, 'length_rsi': 65, 'overbought': 72, 'oversold': 14, 'adx': 26, 'adx_len': 45}. Best is trial 5 with value: 1.353270113741884.
[I 2026-02-22 03:23:35,209] Trial 9 finished with value: -2.620191495570286 and parameters: {'window_rolling_mean': 72, 'window_rolling_std': 95, 'zscore': 3.3306573467170426, 'length_rsi': 64, 'overbought': 91, 'oversold': 43, 'adx': 95, 'adx_len': 51}. Best is trial 5 with value: 1.353270113741884.
[I 2026-02-22 03:23:35,222] Trial 10 finished with value: 0.0 and parameters: {'window_rolling_mean': 5, 'window_rolling_std': 75, 'zscore': 3.3782593601822506, 'length_rsi': 14, 'overbought': 75, 'oversold': 0, 'adx': 74, 'adx_len': 6}. Best is trial 5 with value: 1.353270113741884.
[I 2026-02-22 03:23:35,235] Trial 11 finished with value: 1.620034075632492 and parameters: {'window_rolling_mean': 23, 'window_rolling_std': 62, 'zscore': 1.5853630901105817, 'length_rsi': 80, 'overbought': 67, 'oversold': 33, 'adx': 70, 'adx_len': 7}. Best is trial 11 with value: 1.620034075632492.
[I 2026-02-22 03:23:35,248] Trial 12 finished with value: -1.2779864747743128 and parameters: {'window_rolling_mean': 10, 'window_rolling_std': 36, 'zscore': 1.6404359443984267, 'length_rsi': 94, 'overbought': 65, 'oversold': 34, 'adx': 70, 'adx_len': 6}. Best is trial 11 with value: 1.620034075632492.
[I 2026-02-22 03:23:35,261] Trial 13 finished with value: -4.268077264563584 and parameters: {'window_rolling_mean': 25, 'window_rolling_std': 63, 'zscore': 1.5928069162439304, 'length_rsi': 74, 'overbought': 82, 'oversold': 49, 'adx': 75, 'adx_len': 69}. Best is trial 11 with value: 1.620034075632492.
[I 2026-02-22 03:23:35,274] Trial 14 finished with value: -1.5613915227289015 and parameters: {'window_rolling_mean': 34, 'window_rolling_std': 99, 'zscore': 2.023424947064969, 'length_rsi': 24, 'overbought': 68, 'oversold': 32, 'adx': 65, 'adx_len': 17}. Best is trial 11 with value: 1.620034075632492.
[I 2026-02-22 03:23:35,287] Trial 15 finished with value: 0.7527389578279104 and parameters: {'window_rolling_mean': 16, 'window_rolling_std': 77, 'zscore': 1.022209222854143, 'length_rsi': 79, 'overbought': 77, 'oversold': 32, 'adx': 96, 'adx_len': 40}. Best is trial 11 with value: 1.620034075632492.
[I 2026-02-22 03:23:35,300] Trial 16 finished with value: -4.581039034881837 and parameters: {'window_rolling_mean': 43, 'window_rolling_std': 26, 'zscore': 1.546418070148996, 'length_rsi': 65, 'overbought': 99, 'oversold': 48, 'adx': 85, 'adx_len': 61}. Best is trial 11 with value: 1.620034075632492.
[I 2026-02-22 03:23:35,314] Trial 17 finished with value: 2.8202284889606615 and parameters: {'window_rolling_mean': 18, 'window_rolling_std': 7, 'zscore': 2.3439928328282633, 'length_rsi': 99, 'overbought': 69, 'oversold': 26, 'adx': 38, 'adx_len': 6}. Best is trial 17 with value: 2.8202284889606615.
[I 2026-02-22 03:23:35,327] Trial 18 finished with value: 2.8202284889606615 and parameters: {'window_rolling_mean': 17, 'window_rolling_std': 11, 'zscore': 2.3225023589791416, 'length_rsi': 100, 'overbought': 67, 'oversold': 8, 'adx': 36, 'adx_len': 27}. Best is trial 17 with value: 2.8202284889606615.
[I 2026-02-22 03:23:35,340] Trial 19 finished with value: 0.2735601713033057 and parameters: {'window_rolling_mean': 16, 'window_rolling_std': 5, 'zscore': 2.5447038506245465, 'length_rsi': 100, 'overbought': 62, 'oversold': 5, 'adx': 36, 'adx_len': 28}. Best is trial 17 with value: 2.8202284889606615.
[I 2026-02-22 03:23:35,355] Trial 20 finished with value: 0.0 and parameters: {'window_rolling_mean': 40, 'window_rolling_std': 6, 'zscore': 2.9026427075516783, 'length_rsi': 93, 'overbought': 72, 'oversold': 8, 'adx': 31, 'adx_len': 41}. Best is trial 17 with value: 2.8202284889606615.
[I 2026-02-22 03:23:35,368] Trial 21 finished with value: 0.04321503185360252 and parameters: {'window_rolling_mean': 16, 'window_rolling_std': 31, 'zscore': 2.2537153286301588, 'length_rsi': 85, 'overbought': 67, 'oversold': 24, 'adx': 58, 'adx_len': 7}. Best is trial 17 with value: 2.8202284889606615.
[I 2026-02-22 03:23:35,382] Trial 22 finished with value: 1.2240027184676014 and parameters: {'window_rolling_mean': 20, 'window_rolling_std': 15, 'zscore': 2.23643931362712, 'length_rsi': 99, 'overbought': 57, 'oversold': 28, 'adx': 39, 'adx_len': 13}. Best is trial 17 with value: 2.8202284889606615.
[I 2026-02-22 03:23:35,396] Trial 23 finished with value: 0.0 and parameters: {'window_rolling_mean': 5, 'window_rolling_std': 52, 'zscore': 2.3079426784301194, 'length_rsi': 87, 'overbought': 71, 'oversold': 18, 'adx': 58, 'adx_len': 27}. Best is trial 17 with value: 2.8202284889606615.
[I 2026-02-22 03:23:35,410] Trial 24 finished with value: 0.0 and parameters: {'window_rolling_mean': 34, 'window_rolling_std': 14, 'zscore': 2.9674986773502097, 'length_rsi': 76, 'overbought': 81, 'oversold': 21, 'adx': 24, 'adx_len': 12}. Best is trial 17 with value: 2.8202284889606615.
[I 2026-02-22 03:23:35,424] Trial 25 finished with value: 0.5476658196341967 and parameters: {'window_rolling_mean': 21, 'window_rolling_std': 43, 'zscore': 1.7921446788817152, 'length_rsi': 92, 'overbought': 63, 'oversold': 10, 'adx': 45, 'adx_len': 23}. Best is trial 17 with value: 2.8202284889606615.
[I 2026-02-22 03:23:35,438] Trial 26 finished with value: 2.3318079710462496 and parameters: {'window_rolling_mean': 13, 'window_rolling_std': 63, 'zscore': 2.0986977068704977, 'length_rsi': 80, 'overbought': 59, 'oversold': 37, 'adx': 61, 'adx_len': 5}. Best is trial 17 with value: 2.8202284889606615.
[I 2026-02-22 03:23:35,453] Trial 27 finished with value: 1.5190739789161212 and parameters: {'window_rolling_mean': 10, 'window_rolling_std': 23, 'zscore': 2.1465338138806693, 'length_rsi': 100, 'overbought': 58, 'oversold': 2, 'adx': 38, 'adx_len': 35}. Best is trial 17 with value: 2.8202284889606615.
[I 2026-02-22 03:23:35,467] Trial 28 finished with value: -3.434447823988619 and parameters: {'window_rolling_mean': 11, 'window_rolling_std': 36, 'zscore': 2.4670030593494765, 'length_rsi': 72, 'overbought': 54, 'oversold': 38, 'adx': 53, 'adx_len': 13}. Best is trial 17 with value: 2.8202284889606615.
[I 2026-02-22 03:23:35,481] Trial 29 finished with value: -1.2143140328383053 and parameters: {'window_rolling_mean': 50, 'window_rolling_std': 11, 'zscore': 1.9960845240372174, 'length_rsi': 87, 'overbought': 78, 'oversold': 45, 'adx': 18, 'adx_len': 23}. Best is trial 17 with value: 2.8202284889606615.
[I 2026-02-22 03:23:35,495] Trial 30 finished with value: 0.0 and parameters: {'window_rolling_mean': 32, 'window_rolling_std': 44, 'zscore': 2.8263705835851876, 'length_rsi': 84, 'overbought': 60, 'oversold': 37, 'adx': 3, 'adx_len': 53}. Best is trial 17 with value: 2.8202284889606615.
[I 2026-02-22 03:23:35,509] Trial 31 finished with value: 0.8948447276307032 and parameters: {'window_rolling_mean': 19, 'window_rolling_std': 62, 'zscore': 1.7851952553848756, 'length_rsi': 58, 'overbought': 68, 'oversold': 29, 'adx': 62, 'adx_len': 5}. Best is trial 17 with value: 2.8202284889606615.
[I 2026-02-22 03:23:35,524] Trial 32 finished with value: 1.8871557996191552 and parameters: {'window_rolling_mean': 12, 'window_rolling_std': 68, 'zscore': 2.118831441182053, 'length_rsi': 80, 'overbought': 65, 'oversold': 37, 'adx': 45, 'adx_len': 11}. Best is trial 17 with value: 2.8202284889606615.
[I 2026-02-22 03:23:35,549] Trial 33 finished with value: 0.0 and parameters: {'window_rolling_mean': 13, 'window_rolling_std': 69, 'zscore': 2.4116980506515557, 'length_rsi': 92, 'overbought': 64, 'oversold': 40, 'adx': 41, 'adx_len': 12}. Best is trial 17 with value: 2.8202284889606615.
[I 2026-02-22 03:23:35,571] Trial 34 finished with value: 0.0 and parameters: {'window_rolling_mean': 7, 'window_rolling_std': 69, 'zscore': 2.0730350040490855, 'length_rsi': 69, 'overbought': 71, 'oversold': 36, 'adx': 32, 'adx_len': 19}. Best is trial 17 with value: 2.8202284889606615.
[I 2026-02-22 03:23:35,588] Trial 35 finished with value: -0.09145744901169475 and parameters: {'window_rolling_mean': 89, 'window_rolling_std': 84, 'zscore': 2.648352533153207, 'length_rsi': 81, 'overbought': 60, 'oversold': 29, 'adx': 48, 'adx_len': 11}. Best is trial 17 with value: 2.8202284889606615.
[I 2026-02-22 03:23:35,602] Trial 36 finished with value: -1.6195647945059441 and parameters: {'window_rolling_mean': 28, 'window_rolling_std': 57, 'zscore': 2.1561164173747853, 'length_rsi': 90, 'overbought': 54, 'oversold': 43, 'adx': 43, 'adx_len': 34}. Best is trial 17 with value: 2.8202284889606615.
[I 2026-02-22 03:23:35,617] Trial 37 finished with value: 0.0 and parameters: {'window_rolling_mean': 60, 'window_rolling_std': 50, 'zscore': 2.376347635047536, 'length_rsi': 96, 'overbought': 65, 'oversold': 23, 'adx': 11, 'adx_len': 81}. Best is trial 17 with value: 2.8202284889606615.
[I 2026-02-22 03:23:35,632] Trial 38 finished with value: 0.0 and parameters: {'window_rolling_mean': 39, 'window_rolling_std': 80, 'zscore': 2.653799543504455, 'length_rsi': 56, 'overbought': 75, 'oversold': 27, 'adx': 28, 'adx_len': 19}. Best is trial 17 with value: 2.8202284889606615.
[I 2026-02-22 03:23:35,646] Trial 39 finished with value: 0.0 and parameters: {'window_rolling_mean': 14, 'window_rolling_std': 68, 'zscore': 1.8392395654671547, 'length_rsi': 87, 'overbought': 69, 'oversold': 16, 'adx': 52, 'adx_len': 100}. Best is trial 17 with value: 2.8202284889606615.
[I 2026-02-22 03:23:35,659] Trial 40 finished with value: -4.07948843092467 and parameters: {'window_rolling_mean': 29, 'window_rolling_std': 57, 'zscore': 3.1179371653879824, 'length_rsi': 50, 'overbought': 50, 'oversold': 46, 'adx': 34, 'adx_len': 29}. Best is trial 17 with value: 2.8202284889606615.
[I 2026-02-22 03:23:35,673] Trial 41 finished with value: 2.1803034803497754 and parameters: {'window_rolling_mean': 23, 'window_rolling_std': 63, 'zscore': 1.3336077317135384, 'length_rsi': 78, 'overbought': 66, 'oversold': 35, 'adx': 77, 'adx_len': 10}. Best is trial 17 with value: 2.8202284889606615.
[I 2026-02-22 03:23:35,686] Trial 42 finished with value: -1.1407342595127767 and parameters: {'window_rolling_mean': 20, 'window_rolling_std': 65, 'zscore': 1.2214532755783802, 'length_rsi': 70, 'overbought': 61, 'oversold': 40, 'adx': 81, 'adx_len': 18}. Best is trial 17 with value: 2.8202284889606615.
[I 2026-02-22 03:23:35,700] Trial 43 finished with value: 1.6361264283011965 and parameters: {'window_rolling_mean': 9, 'window_rolling_std': 88, 'zscore': 1.871837960749579, 'length_rsi': 77, 'overbought': 74, 'oversold': 35, 'adx': 46, 'adx_len': 10}. Best is trial 17 with value: 2.8202284889606615.
[I 2026-02-22 03:23:35,715] Trial 44 finished with value: 4.053725477691014 and parameters: {'window_rolling_mean': 23, 'window_rolling_std': 76, 'zscore': 1.4674526274983501, 'length_rsi': 81, 'overbought': 66, 'oversold': 31, 'adx': 59, 'adx_len': 24}. Best is trial 44 with value: 4.053725477691014.
[I 2026-02-22 03:23:35,729] Trial 45 finished with value: 3.063579776024077 and parameters: {'window_rolling_mean': 24, 'window_rolling_std': 80, 'zscore': 1.3684188463674427, 'length_rsi': 61, 'overbought': 55, 'oversold': 31, 'adx': 78, 'adx_len': 24}. Best is trial 44 with value: 4.053725477691014.
[I 2026-02-22 03:23:35,743] Trial 46 finished with value: -2.0393455609062894 and parameters: {'window_rolling_mean': 30, 'window_rolling_std': 74, 'zscore': 1.5026477448633133, 'length_rsi': 45, 'overbought': 55, 'oversold': 30, 'adx': 90, 'adx_len': 24}. Best is trial 44 with value: 4.053725477691014.
[I 2026-02-22 03:23:35,757] Trial 47 finished with value: 1.2366186888814887 and parameters: {'window_rolling_mean': 62, 'window_rolling_std': 92, 'zscore': 1.7002003448759218, 'length_rsi': 32, 'overbought': 58, 'oversold': 26, 'adx': 66, 'adx_len': 44}. Best is trial 44 with value: 4.053725477691014.
[I 2026-02-22 03:23:35,772] Trial 48 finished with value: 0.5273683086415107 and parameters: {'window_rolling_mean': 37, 'window_rolling_std': 80, 'zscore': 1.434066133557657, 'length_rsi': 62, 'overbought': 52, 'oversold': 23, 'adx': 58, 'adx_len': 35}. Best is trial 44 with value: 4.053725477691014.
[I 2026-02-22 03:23:35,786] Trial 49 finished with value: 0.0 and parameters: {'window_rolling_mean': 24, 'window_rolling_std': 18, 'zscore': 1.160354118900242, 'length_rsi': 96, 'overbought': 90, 'oversold': 31, 'adx': 69, 'adx_len': 50}. Best is trial 44 with value: 4.053725477691014.
[I 2026-02-22 03:23:35,799] Trial 50 finished with value: 2.729537388431998 and parameters: {'window_rolling_mean': 26, 'window_rolling_std': 10, 'zscore': 1.3173132951541824, 'length_rsi': 60, 'overbought': 56, 'oversold': 26, 'adx': 62, 'adx_len': 38}. Best is trial 44 with value: 4.053725477691014.
[I 2026-02-22 03:23:35,813] Trial 51 finished with value: 2.0428072014617045 and parameters: {'window_rolling_mean': 44, 'window_rolling_std': 9, 'zscore': 1.3236721626598382, 'length_rsi': 47, 'overbought': 59, 'oversold': 20, 'adx': 61, 'adx_len': 38}. Best is trial 44 with value: 4.053725477691014.
[I 2026-02-22 03:23:35,827] Trial 52 finished with value: 2.9637332916443544 and parameters: {'window_rolling_mean': 27, 'window_rolling_std': 10, 'zscore': 1.4268204436494742, 'length_rsi': 59, 'overbought': 56, 'oversold': 27, 'adx': 54, 'adx_len': 31}. Best is trial 44 with value: 4.053725477691014.
[I 2026-02-22 03:23:35,841] Trial 53 finished with value: 3.0953309445404456 and parameters: {'window_rolling_mean': 27, 'window_rolling_std': 19, 'zscore': 1.123026985978337, 'length_rsi': 59, 'overbought': 54, 'oversold': 25, 'adx': 51, 'adx_len': 32}. Best is trial 44 with value: 4.053725477691014.
[I 2026-02-22 03:23:35,854] Trial 54 finished with value: 2.315219803446283 and parameters: {'window_rolling_mean': 18, 'window_rolling_std': 21, 'zscore': 1.4928008176927727, 'length_rsi': 56, 'overbought': 53, 'oversold': 13, 'adx': 50, 'adx_len': 32}. Best is trial 44 with value: 4.053725477691014.
[I 2026-02-22 03:23:35,868] Trial 55 finished with value: 2.886243033040443 and parameters: {'window_rolling_mean': 32, 'window_rolling_std': 15, 'zscore': 1.0259563781670977, 'length_rsi': 53, 'overbought': 50, 'oversold': 32, 'adx': 55, 'adx_len': 26}. Best is trial 44 with value: 4.053725477691014.
[I 2026-02-22 03:23:35,882] Trial 56 finished with value: 2.8687173082426867 and parameters: {'window_rolling_mean': 35, 'window_rolling_std': 28, 'zscore': 1.082532194918544, 'length_rsi': 39, 'overbought': 51, 'oversold': 33, 'adx': 56, 'adx_len': 46}. Best is trial 44 with value: 4.053725477691014.
[I 2026-02-22 03:23:35,896] Trial 57 finished with value: 1.9565246905120257 and parameters: {'window_rolling_mean': 36, 'window_rolling_std': 26, 'zscore': 1.1201796361503862, 'length_rsi': 39, 'overbought': 50, 'oversold': 34, 'adx': 55, 'adx_len': 47}. Best is trial 44 with value: 4.053725477691014.
[I 2026-02-22 03:23:35,911] Trial 58 finished with value: 2.3551404706943084 and parameters: {'window_rolling_mean': 53, 'window_rolling_std': 31, 'zscore': 1.0003476922360761, 'length_rsi': 53, 'overbought': 52, 'oversold': 32, 'adx': 73, 'adx_len': 60}. Best is trial 44 with value: 4.053725477691014.
[I 2026-02-22 03:23:35,925] Trial 59 finished with value: 2.3075873476289575 and parameters: {'window_rolling_mean': 47, 'window_rolling_std': 18, 'zscore': 1.2423936733170555, 'length_rsi': 43, 'overbought': 56, 'oversold': 28, 'adx': 80, 'adx_len': 30}. Best is trial 44 with value: 4.053725477691014.
[I 2026-02-22 03:23:35,940] Trial 60 finished with value: -0.5627245389700913 and parameters: {'window_rolling_mean': 32, 'window_rolling_std': 27, 'zscore': 1.068836744175645, 'length_rsi': 21, 'overbought': 50, 'oversold': 31, 'adx': 55, 'adx_len': 26}. Best is trial 44 with value: 4.053725477691014.
[I 2026-02-22 03:23:35,955] Trial 61 finished with value: 3.0373163044823417 and parameters: {'window_rolling_mean': 26, 'window_rolling_std': 14, 'zscore': 1.163950001935678, 'length_rsi': 65, 'overbought': 52, 'oversold': 25, 'adx': 66, 'adx_len': 16}. Best is trial 44 with value: 4.053725477691014.
[I 2026-02-22 03:23:35,969] Trial 62 finished with value: 1.6850079290093614 and parameters: {'window_rolling_mean': 27, 'window_rolling_std': 15, 'zscore': 1.2063425867968536, 'length_rsi': 66, 'overbought': 52, 'oversold': 22, 'adx': 68, 'adx_len': 21}. Best is trial 44 with value: 4.053725477691014.
[I 2026-02-22 03:23:35,982] Trial 63 finished with value: 0.6589037217186225 and parameters: {'window_rolling_mean': 42, 'window_rolling_std': 20, 'zscore': 1.3848861039734246, 'length_rsi': 48, 'overbought': 54, 'oversold': 25, 'adx': 50, 'adx_len': 15}. Best is trial 44 with value: 4.053725477691014.
[I 2026-02-22 03:23:35,996] Trial 64 finished with value: 2.5207004729219085 and parameters: {'window_rolling_mean': 23, 'window_rolling_std': 12, 'zscore': 1.1001807143952478, 'length_rsi': 67, 'overbought': 56, 'oversold': 30, 'adx': 65, 'adx_len': 31}. Best is trial 44 with value: 4.053725477691014.
[I 2026-02-22 03:23:36,009] Trial 65 finished with value: 0.0 and parameters: {'window_rolling_mean': 36, 'window_rolling_std': 38, 'zscore': 1.4278556750966984, 'length_rsi': 63, 'overbought': 96, 'oversold': 19, 'adx': 72, 'adx_len': 25}. Best is trial 44 with value: 4.053725477691014.

Best parameters: {'window_rolling_mean': 93, 'window_rolling_std': 93, 'zscore': 2.127317125383313, 'length_rsi': 97, 'overbought': 50, 'oversold': 36, 'adx': 100, 'adx_len': 80}
Best Sharpe Ratio: 7.614743269191434

{'Total Return': np.float64(0.3268047850595117),
 'Sharpe Ratio': np.float64(7.614743269191434),
 'Max Drawdown': np.float64(-0.1080290223515071),
 'Win Rate': 0.5288326300984529}